handle gestures
ubports/unity-system-compositor pull request #11
Opened 2019-12-22 10:28 UTC by wdehoog

handle some key events as gestures by signaling them on a new dbus service com.canonical.Unity.Gestures.

On opo the touch panel notifies some gestures as key events. This pr detects them and signals them on dbus.

2019-12-23 14:21 UTC, mariogrip commented
Thank you! :)

I would like to avoid adding new dbus services under com.canonical namespace, please use com.ubports. We eventually want to rename the others too.

2019-12-27 12:58 UTC, Vince1171 commented
LGTM and works on Oneplus3 @mariogrip

2020-01-22 18:03 UTC, UniversalSuperBox requested changes

2020-01-22 18:03 UTC, UniversalSuperBox commented on src/screen_event_handler.cpp
> +        if (key_code == KEY_POWER)
The indentation in this file seems a bit strange. Could you clean it up so all lines match the style throughout the rest of the file?

2020-01-22 18:03 UTC, UniversalSuperBox commented on src/gesture_event_sink.h
> + * Copyright © 2019 UBports
If you'd like to assign copyright to us, it should be to the UBports Foundation. Additionally, use the full header text, for example what you find at the top of clock.h: https://github.com/ubports/unity-system-compositor/blob/xenial/src/clock.h

2020-02-05 13:38 UTC, UniversalSuperBox requested changes
Thank you for addressing these changes. There are still a few more styling issues.

2020-02-05 13:38 UTC, UniversalSuperBox commented on src/unity_gesture_event_sink.h
> + * Copyright © 2019 UBports
You will want to change to 2020 UBports Foundation here

2020-02-05 13:38 UTC, UniversalSuperBox commented on src/screen_event_handler.cpp
> +                case KEY_ATTENDANT_TOGGLE: gesture_event_sink->notify_gesture("toggle-flash"); break;
You may want to put the `break` statements on the line after the `case` statements. This makes them easier to see when skimming the code.

2020-07-02 18:16 UTC, peat-psuwit commented
What prevents Lomiri from receiving these event codes and processing them directly?

2020-07-02 18:21 UTC, wdehoog commented
@peat-psuwit my goal was having these events available for applications. For example see https://github.com/wdehoog/ubports-misc/tree/master/gestures. I am not very familiar with how events are supposed to be 'flowing' in UT so if this is not the correct way and you can point me another direction I'll look into it.

2020-07-02 19:05 UTC, peat-psuwit commented
Hmm... these events, as input events, are supposed to be received by the foreground application. However, you're trying to signal this to another background application. IMO, USC probably isn't the best place to do this; it should be emitted from Lomiri on the session bus. Also, we may have to think about the key ownership issue.

Just to present some prior art: g-s-d has a thing called `gsd-media-keys`. It talks to GNOME Shell via D-Bus to grab keys. It then either handles events by itself or dispatches other events via D-Bus. The key ownership issue is also handled there.

BTW, currently volume up/down buttons are handled by Lomiri.

2020-07-03 16:38 UTC, wdehoog commented
I will try another approach. Maybe by having Lomiri do the dbus event generation.

2020-07-03 16:38 UTC, closed without merging