[spinner] Add support for wayland backend
ubports/unity-system-compositor pull request #12
Opened 2020-01-19 11:00 UTC by mariogrip

This adds support for wayland backend to the spinner.

It currently defaults to mir if running on an android device and wayland
device if not.

Backend can be overritten by setting COMPOSITOR_BACKEND.

2020-01-21 17:27 UTC, UniversalSuperBox requested changes
I'm still not really sure between up or down on C++, but I know there are some stylistic, grammar, and licensing issues here.

2020-01-21 17:27 UTC, UniversalSuperBox commented on spinner/wayland/eglapp.cpp
> + *             2019 UBports project
UBports Foundation, not project.

2020-01-21 17:27 UTC, UniversalSuperBox commented on spinner/wayland/waylandegl.h
> +#endif //UNITYSYSTEMCOMPOSITOR_WAYLANDEGL_H
Several files are missing a trailing newline

2020-01-21 17:27 UTC, UniversalSuperBox commented on spinner/eglspinner.cpp
> +            printf("Is not android device, defaults to wayland\n");
Consider the following:

"Running on an Android device, using Mir output."

"Not running on an Android device, using Wayland output."

2020-05-12 19:52 UTC, mariogrip commented
Fixed :)

2020-12-18 21:24 UTC, dobey approved these changes
Looks ok and still compiles. Going to merge it since Dalton's comments were addressed and this is for edge.

2020-12-18 21:25 UTC, merged